#!/usr/bin/env luajit
-- PGEC Test Client (ready for CI / automated tests)

local socket   = require("socket")
local crypto   = require("pgec.crypto")
local protocol = require("pgec.protocol")

local username = "jigsaw"
local db_file  = "pgec.db"

print("=== PGEC Test Client ===\n")

-- Load keys generated by create_user.lua
local function load_key(filename)
    local f = io.open(filename, "r")
    if not f then
        error("Key file not found: " .. filename)
    end
    local content = f:read("*all")
    f:close()
    return content
end

local private_key = load_key(username .. "_private.pem")
local public_key  = load_key(username .. "_public.pem")

-- Generate UUID for this session
local uuid = crypto.generate_uuid_v7()
print("Client UUID:", uuid)

-- Connect to server
local host = "localhost"
local port = 9110
print(string.format("Connecting to %s:%d ...", host, port))

local sock = socket.tcp()
sock:settimeout(5)

local ok, err = sock:connect(host, port)
if not ok then
    print("❌ Failed to connect:", err)
    return
end

print("✅ TCP Connected!")

-- Send a raw WebSocket handshake
print("\n--- WebSocket Handshake ---")
local handshake = table.concat({
    "GET / HTTP/1.1",
    "Host: localhost:"..port,
    "Upgrade: websocket",
    "Connection: Upgrade",
    "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==",
    "Sec-WebSocket-Protocol: pgec",
    "Sec-WebSocket-Version: 13",
    "",
    ""
}, "\r\n")

sock:send(handshake)

-- Read handshake response
local response = sock:receive("*l")
print("Server response:", response or "(none)")

if response and response:match("101") then
    print("✅ WebSocket handshake successful!")
else
    print("❌ WebSocket handshake failed")
    sock:close()
    return
end

-- Example: send a "hello" + signature message (simulate your protocol)
local hello_msg = "hello("..uuid..")"
local signature = crypto.sign(hello_msg, private_key)

print("\nSending hello with signature...")
sock:send(hello_msg .. "|" .. signature .. "\n")

-- Normally here you would receive and parse server responses according to protocol
local server_reply = sock:receive("*l")
print("Server reply:", server_reply or "(none)")

sock:close()
print("\n✅ Test client finished")